
# project level settings
data_rootdir        : C:/Users/Hamidreza.Zoraghein/Google Drive/Population_Downscaling_1KM
datadir_histdata    : main_inputs
datadir_future      : ssp_projections
point_indices       : Point_Indices.txt
ssp_code            : SSP2
region_code         : Pennsylvania
datadir_output      : outputs

# run settings
compute_params      : true
compute_proj        : true
start_year          : 2000
end_year            : 2050
time_step           : 10


