# Example config.yml file

grid_coordinates_file: '/Users/d3y010/repos/github/spatial_population_downscaling_model/population_gravity/tests/data/inputs/rhode_island_coordinates.csv'
historical_rural_pop_raster: '/Users/d3y010/repos/github/spatial_population_downscaling_model/population_gravity/tests/data/inputs/rhode_island_rural_2010_1km.tif'
historical_urban_pop_raster: '/Users/d3y010/repos/github/spatial_population_downscaling_model/population_gravity/tests/data/inputs/rhode_island_urban_2010_1km.tif'
historical_suitability_raster: '/Users/d3y010/repos/github/spatial_population_downscaling_model/population_gravity/tests/data/inputs/rhode_island_mask_short_term.tif'
projected_population_file: '/Users/d3y010/repos/github/spatial_population_downscaling_model/population_gravity/tests/data/inputs/rhode_island_SSP2_popproj.csv'
one_dimension_indices_file: '/Users/d3y010/repos/github/spatial_population_downscaling_model/population_gravity/tests/data/inputs/rhode_island_within_indices.txt'
output_directory: '/Users/d3y010/repos/github/spatial_population_downscaling_model/population_gravity/tests/data/outputs'
alpha_urban: -2.0
alpha_rural: -0.34
beta_urban: 0.46
beta_rural: 1.0
scenario: 'SSP2'
state_name: 'rhode_island'
historic_base_year: 2010
projection_start_year: 2020
projection_end_year: 2030
time_step: 10
