
# project level settings
data_rootdir        : /Users/d3y010/projects/population
datadir_histdata    : Main_Inputs
datadir_future      : ssp_projections
point_indices       : Point_Indices.txt
ssp_code            : SSP2
region_code         : District of Columbia
datadir_output      : outputs

# run settings
compute_params      : true
compute_proj        : false
start_year          : 2000
end_year            : 2050
time_step           : 10


